log:
  level: debug

executor:
  datasources:
    - id: postgres1
      postgres:
        # ensure that pgstreamer has been created and the user has replication privileges
        url: "postgres://postgres:postgres@localhost:5432/postgres"
        # SQL command to create publication if it does not exist. See examples here: https://www.postgresql.org/docs/current/sql-createpublication.html
        createPublications: ['CREATE PUBLICATION demo_publication FOR ALL TABLES;']

    - id: kafka1
      kafka:
        brokers: ["localhost:9094"]

  connectors:
    - id: postgres1->kafka1
      from: postgres1
      to: kafka1
      allCollections: true
      # only stream specific tables (default behaviour is to stream all tables)
      # mapping:
      #   - from: users
      #     to: users-topic
      #     # map only name field from users table
      #     fields:
      #       - name: name

    # - id: staging->staging
    #   from: staging-postgres
    #   to: staging-kafka
    #   mapping:
    #     - from: posts
    #       to: posts-topic
    #       # map all fields (default behaviour)
    #       allFields: true
    #     - from: users
    #       to: users-topic
    #       where: "email LIKE '%@gmail.com'"
    #       fields:
    #         - name: name
    #           transform: "uppercase"
    #         - name: email
